### PR TITLE
Hello Microverse Project

### PR DESCRIPTION
**Pull request by elad237**
# In this pull request, I was able to:
     - I create the branch microvers_linter
     - Create index.html file and add # Hello Microverse # to the `h1` tag.
     - Create style.css and style the content of the `h1` tag inside it.
     - Create `.gitignore` file and add test.md and node-modules to ignore them.
     - I add linters

### CODE REVIEW

**Review by Qoosim — CHANGES_REQUESTED** [review]
#   *Status: Required Changes* :recycle:

Hi @elad237, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

-  No linter errors. :heavy_check_mark:
-  Correct GitHub Flow. :heavy_check_mark: 



## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

- [ ] Good job so far. However, there're few things you need to work on before you can move to the next project. First of all, a good pull request must have a good titile. For this project, something like `Hello Microverse Project ` is a good PR title instead of `First commit of branch microvers_linter` title. It does not carry any related meaning to the PR you are making. Kindly correct that.

- [ ] Also, a good PR should have a brief description of what you've worked on in the PR. There's no description in your PR. Something like :point_down: 
```
    In this pull request, I was able to:
     -  Set up the linters.
     -  Create index.html file and add # Hello Microverse # to the `h1` tag.
     -  Create style.css and style the content of the `h1` tag inside it.
     -   Create `.gitignore` file and add test.md and node-modules to ignore them.
```
This is your current PR description section looks like :point_down: 

description

Kindly look into this and modify your PR status.

- [ ] A good project must have an informative descriptive README. You readme file is too scanty. Kindly look into this [template](https://github.com/microverseinc/readme-template/blob/master/README.md) from Microverse and customize it to suit your need.

**Review by christianbiring1 — CHANGES_REQUESTED** [review]
Hi @elad237 :wave: , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
# STATUS: REQUEST CHANGES :recycle: 
164625215-44f24c98-53c8-49c1-b68f-05723a584dc2


 ## Highlights
- [ ] All linters tests are green
- [ ] Some general requirements are met

 ## Required Changes ♻️
### Kindly make sure implement all the changes suggested by the previous reviewer
- [ ] Pull request must have a descriptive `title`. For this project, something like `Hello Microverse Project` is a good PR title instead of the `First commit of branch microvers_linter` title. It does not carry any related meaning to the PR you are making. Kindly correct that. You can click on the `edit` button on the top right in the same line as your PR title and change it.
- [ ] Also, a good PR should have a brief description summary of what you've worked on in the PR. There's no description in your PR. Something like :point_down: 
  In this pull request, I was able to:
     `-  Set up the linters.`
     `-  Create index.html file and add # Hello Microverse # to the `h1` tag.`
     `-  Create style.css and style the content of the `h1` tag inside it.`
     `-   Create `.gitignore` file and add test.md and node-modules to ignore them.`
To do so,You can click those three dots on top on the description box and you will be able to `edit` 
Screenshot from 2022-09-22 23-04-20

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Felix45 — CHANGES_REQUESTED** [review]
Hi @elad237 :clap: , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.



 ## Highlights :heavy_check_mark: 
 - Linter checks are passing
 - Correct GitHub flow is used

 ## Required Changes ♻️
- [x] As requested by a previous reviewer, please amend the title of this pull request to a descriptive title that describes the new changes in the pull request. You could amend the title to a more descriptive title like `Hello Microverse Project` instead of `First commit of branch microvers_linter`

- [x] Please consider adding a brief summary of all the changes introduced in this pull request in the description section of the pull request as requested by a previous reviewer. You can achieve this by editing the current summary see screenshot below :point_down: .

Screenshot from 2022-09-23 03-16-11

To edit the summary please click on the three dots in the image above, copy the text below and paste it under the `Write` tab of the editor, then click _Update Comment_
```
## In this pull request I was able to

- Set up the linters.
- Create index.html file and add # Hello Microverse # to the h1 tag.
- Create style.css and style the content of the h1 tag inside it.
- Create .gitignore file and add test.md and node-modules to ignore them.
```
- [x] As requested by a previous reviewer please consider updating your readme to have a more professional look. Kindly use this [readme template](https://github.com/microverseinc/readme-template/blob/master/README.md) from Microverse and customize it to your project.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by christianbiring1 — COMMENTED** [review]
Hi @elad237 :wave: , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# Invalid Code Review Request :red_circle: :crossed_swords: 

You have submitted a project, that 
- [ ] Has conflict with the base branch, Kindly make sure the conflict is resolved before you re-submit your work
You can check [here](https://youtu.be/RGOj5yH7evk?t=2702) how to resolve a conflict on a Pull Request

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by nedjwab — APPROVED** [review]
# 🟢 Project Approved! 🏆

## Hi @elad237    👋

Your project is complete! ✔️ 🏁

Your code was very professional 💯

There is nothing else to say other than... _it's time to merge it_ :shipit:
Congratulations! 🎉

 
## Highlights 🌟

- ✔️ Descriptive commmit messsages
- ✔️ Descriptive PR description
- ✔️ No linter Errors
- The code is top-notch! 💯 and have a huge potential.

Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.


_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
